name: Merge workflows

on:
  workflow_dispatch:
  push:
    branches:
      - 'workflows'

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Merge Branches
        run: |
          branches=$(git branch --list | cut -c 3-)

          for branch in $branches; do
            if [ "$branch" != "workflow" ]; then
              git switch $branch
              git merge workflow --no-commit
            fi
          done
          git push https://${{ secrets.MAVEN_REPO_TOKEN }}@github.com/tsechelidisMichail/HSMB-v3.git --all
      
